flags: {}
extra-package-dbs: []
packages:
- '.'
- location: /home/j/dev/apps/haskell/libraries/11-bitmask
  extra-dep: true
- location: /home/j/dev/apps/haskell/libraries/12-GenericPretty
  extra-dep: true
extra-deps: []
resolver: nightly-2016-10-14
